---
title: Three things I learned from a year of listening to musical theatre that I didn't learn in my Classical training
author: Yeng Miller-Chang
date: '2022-03-19'
slug: a-year-of-theatre
tags:
  - broadway
  - music
  - music-theory
  - musical-theatre
---

*Views and opinions expressed are solely my own.*

## Introduction

About one year ago, I started listening and playing musical theatre music for piano, as someone who had been playing primarily Classical (common-practice) piano music for most of my life. Here, I will outline some of the lessons I learned since venturing in this direction.

## Listening to musical theatre music opened my ears to new possibilities. 

In Classical music, we are taught that the building block of every chord is the [triad](https://en.wikipedia.org/wiki/Triad_(music)), and that (as a slight oversimplification) chords outside of triads and [seventh chords](https://en.wikipedia.org/wiki/Seventh_chord), notes lying outside of these basic chords are [nonharmonic tones](https://en.wikipedia.org/wiki/Nonchord_tone) which are to be resolved.

### Suspended (or sus) chords

Most musical theatre music does not work that way. One of the first musicals I dived into was *Dear Evan Hansen*, of which one of its songs (linked below) opens immediately with a three-chord motif, the third chord which is a known as a [sus chord](https://en.wikipedia.org/wiki/Suspended_chord).

<iframe width="560" height="315" src="https://www.youtube.com/embed/kfnMvo87fQU" frameborder="0" allowfullscreen></iframe>

Sus, or suspended, chords are viewed in Classical music curricula as chords that must be resolved to a triad. The sus chord indicated above does not resolve in the Classical sense at all; in fact, it is treated as a fundamental motif to be emphasized throughout the piece.

### 7th chords and extensions

Classical music curricula do not cover the uses of chords with a major third and a major 7th above the root. However, such chords can be used effectively without having to think about specific function. See, for example, the prologue of *Into The Woods*, which has repeating major-major 7th chords throughout the piano part.

<iframe width="560" height="315" src="https://www.youtube.com/embed/joNRtJXWQvQ" frameborder="0" allowfullscreen></iframe>

### Other devices

There are other devices, such as [slash chords](https://en.wikipedia.org/wiki/Slash_chord) and [power chords](https://en.wikipedia.org/wiki/Power_chord) that come up occasionally in musical theatre music that are not given any explanation in Classical music curricula.

### Misconceptions from the Classical music world

In speaking to many of my peers who are Classically trained, there is a misconception that "popular" music tends to be much simpler harmonically than most classical music. I've found the contrary to be true, quite frankly.

## Listening to musical theatre music gave me a better appreciation for the usage of lyrics.

Very little time in Classical music education is spent on songwriting. In tandem with the wider variety of chords that are used in musical theatre, lyrics play a crucial role in music.

In a lot of Classical music, there is a primary reliance on melody in tandem with harmony for expression. However, I have learned, as a general rule, it is difficult for most audiences outside of those who listen to Classical music frequently to appreciate this mode of expression. For this reason, **lyrics serve a crucial role for helping a general audience relate to a musical's subjects.** 

Classical music education should spend time not only emphasizing melody and harmony, but also how lyrics can be used as a mode of expression, such as through [*Songwriting: Writing the Lyrics*](https://www.coursera.org/learn/songwriting-lyrics) by Pat Pattison. 

Stephen Sondheim was very well-known in the musical theatre world for his use of lyrics; I point to "Move On" from *Sundays in the Park with George*.

<iframe width="560" height="315" src="https://www.youtube.com/embed/m2QTNOv6VS0" frameborder="0" allowfullscreen></iframe>

## Harmonic simplicity does not imply technical simplicity.

Aside from the difficulties that arise from trying to play piano with a larger ensemble, there are some piano works from the Broadway world that, though seemingly simple harmonically, require substantial endurance of the piano player. Two such examples are given below.

<iframe width="560" height="315" src="https://www.youtube.com/embed/d31BBuz7ApQ" frameborder="0" allowfullscreen></iframe>

<iframe width="560" height="315" src="https://www.youtube.com/embed/_024TJ1Daok" frameborder="0" allowfullscreen></iframe>

It is difficult to get both of these pieces up to tempo, and if they are not approached correctly, it is easy to tense up. 

## Conclusion

There is so much one can learn about music that a Classical music training quite frankly misses. Such tools can be used to inform performance and composition practices (I find these particularly useful from the composition perspective). From my perspective, diving into musical theatre is only the beginning. 